
FROM tiangolo/uwsgi-nginx-flask:flask

RUN apt-get update
RUN apt-get -y install default-jdk
RUN apt-get -y install ca-certificates
RUN apt-get -y install build-essential python-dev libssl-dev libffi-dev
RUN apt-get -y install python-mysqldb

COPY timeout.conf /etc/nginx/conf.d/timeout.conf

COPY requirements.txt /tmp/

COPY . /tmp/SDGSCompetence/

RUN pip install -U pip
RUN pip install urllib3 pyasn1 ndg-httpsclient pyOpenSSL
RUN pip install -r /tmp/requirements.txt

COPY ./app /app

WORKDIR /tmp/SDGSCompetence

RUN python setup.py install

WORKDIR /tmp

RUN apt-get install git

WORKDIR /app

ENV MESSAGE "SDGSCompetence is running..."



